# Generated by Django 5.2.4 on 2026-03-04 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                (
                    "parse_mode",
                    models.CharField(
                        choices=[
                            ("HTML", "HTML"),
                            ("Markdown", "MarkdownV2"),
                            ("Plain", "Plain Text"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "tag",
                    models.CharField(
                        choices=[
                            ("domain_check", "Domain Check"),
                            ("kva_test", "KVA Test"),
                            ("asana_farm_comments", "Asana Farm Comments"),
                            ("p1sms_balance", "P1SMS Balance"),
                            ("offer_reawake", "Offer Reawake"),
                            ("onboarding", "Onboarding"),
                            ("hr_vacation", "HR Vacation"),
                            ("luckstar_accounts", "Luckstar Accounts"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "В очереди"),
                            ("sent", "Отправлено"),
                            ("error", "Ошибка"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("send_at", models.DateTimeField(blank=True, default=None, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Сообщение Telegram",
                "verbose_name_plural": "Сообщения Telegram",
                "ordering": ("-created_at",),
            },
        ),
    ]
