services:
  atl-poligon-web:
    build: .
    volumes:
      - ./app:/app
      - ./.env:/app/.env
    env_file:
      - ./.env
    expose:
      - 8000
  nginx:
    image: nginx:alpine
    ports:
      - "${NGINX_PORT}:82"
    volumes:
      - ./nginx_extra.conf:/etc/nginx/conf.d/uploads.conf:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./app/static:/app/static
      - ./app/media:/app/media
      - /etc/letsencrypt:/etc/letsencrypt:ro