networks:
  shared-net:
    external: true

services:
  atl-poligon-web:
    build: .
    volumes:
      - ./app:/app
      - ./.env:/app/.env
    env_file:
      - ./.env
    expose:
      - 8000
    networks:
      - shared-net
